### ISSUE TITLE
Function Request - Load Wallet on Log On

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#15]
Add an option so the wallet automatically opens (Fullnode GUI) when the operating system starts.
This would have to be an on/off function.

I raise this issue because a lot of our users (especially windows) are suffering due to an absurd amount of updates that reboot the PC, would be useful if they had the option to simply open the wallet and the blockchain was already updated. Also a good warning that something happened to people that keep the wallet on their tray.

**Comment by DennisAMenace** [comment]
If this is for automatic updates, they would still need to login in order for xCore to launch. The UI will only load after the user logs in when they return.
