### ISSUE TITLE
Bug - Wallet Send Function UI Coin Error

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#16]
When you put a zero amount on the wallet is shows up as Stratis.

![image](https://user-images.githubusercontent.com/59352730/71644571-4a8bea00-2ca9-11ea-90dd-9ac3f3d3692d.png)

**Comment by DennisAMenace** [comment]
This is a bug in the x42-FullNode-UI - Please wait to for xCore before submitting bugs.
