### ISSUE TITLE
Function Request - Balance to BTC and Local Currencies

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#18]
This extra function, especially with several supported currencies would be appreciated.

![image](https://user-images.githubusercontent.com/59352730/72557267-2b7f8180-387f-11ea-9368-b80c5d16b78b.png)

**Comment by Gabriel-x42** [comment]
A bounty of 1000 x42 has been added to anyone who delivers the code for this function.
The pull request MUST be approved and merged before the bounty is paid.

**Comment by dimsavva** [comment]
Code implemented and merged

**Comment by dimsavva** [comment]
This was included in a prior release and can be closed
