### ISSUE TITLE
Color Schemes

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#24]
Bug Description:

Under light colors:
The 'Mixed Colors' and 'Blue' color schemes are switched.

Under dark colors:
The 'Blue' scheme doesn't match the wallet feel, same for the 'Pink'.

**Comment by Myke500** [comment]
@Gabriel-x42 
This is resolved> "Under light colors:
The 'Mixed Colors' and 'Blue' color schemes are switched."

**
**Please check v-b42 and see if the dark colors match " _the wallet feel_"**
