### ISSUE TITLE
Bug - Coin Transfer

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#26]
Bug Description:
When transferring coins from cold wallet. It will show that it takes 10 away but adds 1000 or so. The main wallet shows it transferred the correct amount but the cold wallet transaction history doesn't correct it's self. However. The delegated balance will also drop by what it says in the transaction history. Once the coins have been validated. It will return to correct amount minus the coins that were transferred.

Steps to reproduce the bug:
https://cdn.discordapp.com/attachments/484409126286393364/672970430675681290/Cold_Wallet_Transfer.gif

Desktop (please complete the following information if applicable):

OS: Windows 10

Bug found on discord by Juno

**Comment by DennisAMenace** [comment]
We are hiding the change transactions on the main dashboard, But not on the cold staking history, because of the nature of cold staking, you don't have change addresses, so we cannot hide it.
