### ISSUE TITLE
Bug - Cannot Unlock Staking

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#27]
Bug Description:
On the testnet I've received a large test coin transaction on a new wallet that received a POS v4.0 transaction that never showed up. Now I am unable to unlock staking with this particular wallet.

Steps to reproduce the bug:

Go to xCore-b6
Receive a new transaction
Click on Unlock staking by entering your password
See bug
![image](https://user-images.githubusercontent.com/59352730/73612245-d787d300-45c8-11ea-8f9f-c5f26dfd8b55.png)

Expected Behavior:
Wallet is expected to unlock at this point.
If oyu click on stop staking it will briefly flash the staking weight of the network and your staking weight as 9.

Desktop (please complete the following information if applicable):
OS:  Windows 10 enterprise

**Comment by DennisAMenace** [comment]
Cannot reproduce. Please give reproduction steps from a zero balance.
