### ISSUE TITLE
Bug - bad-txns-inputs-missing

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#28]
Bug Description:
When trying to make transactions a bad-txns-inputs-missing message is popping up as we try to make regular txs on the testnet.

Steps to reproduce the bug:

01. Go to xCore-b6, open it and unlock it
02. Click on Send
03. Enter the receiving address and amount, enter your password
04. See error
![image](https://user-images.githubusercontent.com/59352730/73614780-eed2ba80-45e0-11ea-9ca6-8d1769a67f54.png)

Expected Behavior:
Transaction is expected to go through without any issues.

Desktop (please complete the following information if applicable):
OS: Windows 10 enterprise

**Comment by DennisAMenace** [comment]
Cannot reproduce. Please give reproduction steps from a zero balance.
