### ISSUE TITLE
Feature Request - Rescan wallet click option

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#29]
Is the feature you are request related to a problem? Please describe it in detail:
When trying to rescan a wallet one is not able to simply click the month or year number to choose.

Describe the solution you would like:
An option that allows users to click on the month and year to quickly scroll to the exact month they want. This will be especially useful in a few years.

**Comment by Myke500** [comment]
This feature has been added.  
![image](https://user-images.githubusercontent.com/17334141/99738541-92615e80-2a7f-11eb-8dae-c2a1c1b262ea.png)
