### ISSUE TITLE
Function Request - 'Send all available balance' option

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#30]
Is the feature you are request related to a problem? Please describe it in detail:
When clicking 'Send' an option to auto-fill all available balance would be a good addition.

Describe the solution you would like:
The send all available is pretty useful, but we may want to go a step further and have increments, 10, 25, 50% of available balance or other similar step numbers related to how much balance there is.
But just the send all all available is already a great option! Just clicking the available balance to auto-fill the amount would be more than enough.

![Screenshot_2](https://user-images.githubusercontent.com/59352730/73687031-f0b38100-46a7-11ea-84b1-4a5fc58b80dd.png)

**Comment by Myke500** [comment]
![image](https://user-images.githubusercontent.com/17334141/99740372-b888fd80-2a83-11eb-8291-4dff87f3a08c.png)


This has been added as an option.  

I would like to see it be changed visually.  Like a "MAX" button as seen on the delegate transaction box

![image](https://user-images.githubusercontent.com/17334141/99740489-fb4ad580-2a83-11eb-8d97-a013a8548c88.png)
