### ISSUE TITLE
Function Request - Total Stakes Earned

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#32]
Describe the solution you would like:
A good addition to xCore would be a 'total stakes earned' toggle option on the main wallet.
Showing how much that particular user has earned only through stakes would not only be interesting but a good way to track how much x42 a set amount of staking coins are generating.
In addition to other function requests like fiat coin value, this could be cycled when clicking that total amount to show how much that is worth in btc, usd and several other currencies that the user chose to have it available via their settings.

**Comment by Myke500** [comment]
** Add a stake counter to the user interface. **

Something that keeps track of the __daily, weekly, monthly, yearly__ total of stakes received and total of accumulated coins during that time.

**Comment by Gabriel-x42** [comment]
A bounty of 5000 x42 has been added to anyone who delivers the code for this function.
The pull request MUST be approved and merged before the bounty is paid.

**Comment by dimsavva** [comment]
I'll take this one.

**Comment by dimsavva** [comment]
Working on this

**Comment by Gabriel-x42** [comment]
Issue resolved and bounty paid out to @dimsavva.
