### ISSUE TITLE
Function Request - Add coin value to UI

### ISSUE THREAD

**Issue by Myke500** [x42protocol/xCore#33]
Add coin price/value to user interface for user convenience

Global Average recommended

**Comment by Gabriel-x42** [comment]
A bounty of 1000 x42 has been added to anyone who delivers the code for this function.
The pull request MUST be approved and merged before the bounty is paid.

**Comment by dimsavva** [comment]
@Gabriel-x42 would you be happy for this feature to be implemented using the coingecko api?
https://api.coingecko.com/api/v3/simple/price?ids=x42-protocol&vs_currencies=USD

**Comment by Gabriel-x42** [comment]
> @Gabriel-x42 would you be happy for this feature to be implemented using the coingecko api?
> https://api.coingecko.com/api/v3/simple/price?ids=x42-protocol&vs_currencies=USD

Definitely!

**Comment by dimsavva** [comment]
Code implemented and merged - New enhancement PR will coming soon.

**Comment by Gabriel-x42** [comment]
Bounty paid out, issue resolved by @dimsavva.
