### ISSUE TITLE
Function Request - Vanity Seed Words

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#34]
Describe the solution you would like:
Having an option to generate your own seed words would be very much appreciated.
A lot users know songs, poems and other sorts of written text by heart, it would be an interesting way to add another layer of security to seed words.

**Comment by Myke500** [comment]
This is already an available option but is not obvious.  To use this method, a user would choose the restore option, and enter seed words of their own choosing.  

Could you provide more details of your expectations after trying this?
