### ISSUE TITLE
Wallet Streamlining - Text

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#38]
Is the feature you are request related to a problem? Please describe it in detail:
There are several types of capitalization being used on our wallet, some places are written without capitalized letters, others aren't, a good example would be the advanced options.

![image](https://user-images.githubusercontent.com/59352730/85211438-9bf36880-b31f-11ea-97c0-11317bf45c1e.png)

Describe the solution you would like:
We should use just one default on the entire wallet, be it 'Fullnode version' or 'Fullnode Version' it matters little, as long as it is all equal.

Very minor improvement that makes a bit of a difference on the end product.

Also, on our advanced options we have 'Cold Staking Wallet Type' and it is showing 'cold' and 'hot', should it be just 'Staking Wallet Type'?

![image](https://user-images.githubusercontent.com/59352730/85211465-dbba5000-b31f-11ea-88a8-35eea13d9ff6.png)

**Comment by Myke500** [comment]
This will be addressed in one of the next updates.
