### ISSUE TITLE
Some text displayed incorrectly 

### ISSUE THREAD

**Issue by Myke500** [x42protocol/xCore#41]
There are some places where the text " **<br>** " is shown.

01. Go to create new wallet
02. Click on make a new wallet and confirm it
03. Wallet Created confirmation shows as seen in image below

xServer WINDOWS version 
![image](https://user-images.githubusercontent.com/17334141/85795051-7b932780-b6ec-11ea-8a88-90cd946c0e37.png)

**Comment by DennisAMenace** [comment]
Fixed ref: https://github.com/x42protocol/xCore/commit/1a6503cf786c4b4f9e0ba98339d2bc5dc8c13d44
