### ISSUE TITLE
Function Request - UI xServer Connections Breakdown

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#46]
Describe the solution you would like:
Add an UI option to break down how many t1's to t3's the xCore is connected.
This would better fit in the advanced window somewhere, or in the tooltip that already shows xCore and xServer connections.

**Comment by Gabriel-x42** [comment]
A bounty of 500 x42 has been added to anyone who delivers the code for this function.
The pull request MUST be approved and merged before the bounty is paid.

**Comment by dimsavva** [comment]
Working on this

**Comment by Gabriel-x42** [comment]
Issue resolved and bounty paid out to @dimsavva.
