### ISSUE TITLE
Function Request - Dump Addresses to .txt file

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/xCore#47]
Describe the solution you would like:
On advanced, under 'Generate Addresses' there should be an option to save the generated addresses to a .txt file.
I believe the best configuration for this text would be one address per line, no spaces. This .txt file should be able to interact with the multi-send function that was posted on another function request.

**Comment by Gabriel-x42** [comment]
A bounty of 1000 x42 has been added to anyone who delivers the code for this function.
The pull request MUST be approved and merged before the bounty is paid.

**Comment by boozee** [comment]
Next one I'm working on

**Comment by dimsavva** [comment]
This was included in a prior release and can be closed
