### ISSUE TITLE
TAB to next box - 

### ISSUE THREAD

**Issue by Myke500** [x42protocol/xCore#65]
During wallet creation the screen for confirming secret words does not move the text input to the next box when tab is used

Describe the solution you would like:
It would be great to be able to tab to the next input box during this process.

Screenshots:

![image](https://user-images.githubusercontent.com/17334141/109318013-30dd2880-7802-11eb-865f-615ff6cc6f0e.png)

**Comment by beowulf518** [comment]
I can do it with $60.

**Comment by beowulf518** [comment]
I can solve this for $60

**Comment by Gabriel-x42** [comment]
A bounty of 500 x42 has been added to anyone who delivers the code for this function.
The pull request MUST be approved and merged before the bounty is paid.

**Comment by boozee** [comment]
I'm working on this one, should be ready and fully tested soon

**Comment by Gabriel-x42** [comment]
Issue resolved by @boozee, bounty paid off.
